
//test the registration POST http://localhost:4000/api/user Content-Type: application/json

{
"FullName": "test",
"Username": "test", "Password": "pass", "Email": "nureg@gmail.com"

}

###

//test to add song to playlist POST http://localhost:4000/api/user/playlist Content-Type: application/json

{ "Playlist_name": "example2", "user_id": 2 }

###

//test to get all users and playlists GET http://localhost:4000/api/user

###

//test to get user by id and its playlists GET http://localhost:4000/api/user/2

###