
//test the registration 
POST http://localhost:4000/api/user 
Content-Type: application/json

{
"FullName": "dino nino",
"Username": "nino", "Password": "123abc", "Email": "nino@mail.com"

}

###

//Create new playlist 
POST http://localhost:4000/api/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjU4NTAyNywiZXhwIjoxNjMyNjcxNDI3fQ.0Oyd1OAPs3vKkWOzpUw2-AmYDBeW2QtjyWa9jaCkoMY
Content-Type: application/json

{ "Playlist_name": "test 3"}

###

//test to get all users and playlists 
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjU4NTAyNywiZXhwIjoxNjMyNjcxNDI3fQ.0Oyd1OAPs3vKkWOzpUw2-AmYDBeW2QtjyWa9jaCkoMY

###

//Get user by id and its playlists 
GET http://localhost:4000/api/userplaylist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjU4NTAyNywiZXhwIjoxNjMyNjcxNDI3fQ.0Oyd1OAPs3vKkWOzpUw2-AmYDBeW2QtjyWa9jaCkoMY

###

DELETE   http://localhost:4000/api/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjQ2ODI2MiwiZXhwIjoxNjMyNTU0NjYyfQ.KK9yUeMt1ScEyam1lpqsxZUFUydW1W7k7tORnhKjXPk
Content-Type: application/json

{ "id": "5"}

###
POST http://localhost:4000/api/playlist/song
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjgwNTM5OCwiZXhwIjoxNjMyODkxNzk4fQ.eENb1qL-AoHh5CXC1yNfVO3noR84KR3h9y5rqS36Epk
Content-Type: application/json

{"playlist_id": "51", 
"song_id": "N4KvafPbauw10",
"song_name": "Eet", 
"artist": "Regina Spektor", 
"album": "Far" }