
//test the registration 
POST http://localhost:4000/api/user 
Content-Type: application/json

{
"FullName": "dino nino",
"Username": "nino", "Password": "123abc", "Email": "nino@mail.com"

}

###

//test to add playlist 
POST http://localhost:4000/api/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjQwNjExMSwiZXhwIjoxNjMyNDkyNTExfQ.gnneYwxzn5yOUwkhKok7EWDBHeoKh4yFqpVh7au-Xd0
Content-Type: application/json

{ "Playlist_name": "updatetest"}

###

//test to get all users and playlists 
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTYzMjI1NDEwNCwiZXhwIjoxNjMyMzQwNTA0fQ.IeYwYabpgAAlWkc7GJcxZcxWQSoZ8GtM4tl6mPV0jpE

###

//test to get user by id and its playlists 
GET http://localhost:4000/api/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTYzMjI1NDEwNCwiZXhwIjoxNjMyMzQwNTA0fQ.IeYwYabpgAAlWkc7GJcxZcxWQSoZ8GtM4tl6mPV0jpE

###

DELETE   http://localhost:4000/api/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMjQ2ODI2MiwiZXhwIjoxNjMyNTU0NjYyfQ.KK9yUeMt1ScEyam1lpqsxZUFUydW1W7k7tORnhKjXPk
Content-Type: application/json

{ "id": "5"}